credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "ubuntu"
          password: "{AQAAABAAAAAQwwzxviauGvCtjlYEvP5OHv6bslrq6kh4BJ/VW83dM68=}"
          scope: GLOBAL
          username: "ubuntu"
      - basicSSHUserPrivateKey:
          id: "ubuntu-creds"
          privateKeySource:
            directEntry:
              privateKey: "{AQAAABAAAAowYcmdDViUL8D8Z03FLGQ0PdVoLuu0XdRn0rmmPWChAYNv7f7uNNvKWs9Ukb5PEFGT9UK2ZC7AUs0hlivHSmi/jvxQReQgyzaJf9oxv1z1mEeI7c4029FpD/nLGf6tkyoPhLNBX+agl7AEh9iOvMh0pwqm6HgdpohhrIlAb7e3I6bXOfKD1T3phTS0wZ9aZawShsaVCJLQn9O0ayDOw7DX/cgUfD4OPr6BSM5RmZJtEw/bk4tpb5mrSSb8lUuZfsrI9Nbgrwbr8iyz0pOgJ1uAXcZNamEe9cgDgx9c1W+dI5v4pWpqsqvIkJOIlN5DHPZwOwdzS0ntrhz7q5EkZwtuFLEmcRKENfgKixUajLZNDTElMYn34uqY+LusvUxPLLqESjB326sPmwpIiZFMLlJ8AzuCKHwMRwP4mE8ky/asBUCEMDFKe2xdgp6BcWC9cupv3jFBOWtB3c6OzvhV0qUXVtGekioWiTKBbTHn8dpVifAHkURUbA4LiAbzXvCMq+IzN+MwcQ/uZvm7opYW6mMZnGGhCsa+T3TbtGiMMaBfu3DlTODN6E1Gv52Tl16YTB5QRPvIsNfJwNq4Lz8+k2RA30FHz7GCuRnkUqiFvRmD5PAkzkQ0rZ09g0MpxNxLeVp1kLqji15YiiW74tIqHoFtmpym4uEdb8hTdxXoSlxziRcnfidIvnoYPCTjBLtvROBM+znBdk40NMoSOcD/fNRg7CrRZmQWoUX7CLRVovfBAlnZs4u6eGolfABPPzgmjyE+XwbAfwfGwi8Kk/Kn2TMiJ/KGvpTefs0yENz9x+El3kQMXMVPDVSKbOTqYglV2Z1GY5INUq9SxDIuKZ9/VPi9pnztnu+7L31PVHqWGk3K5P27lAFKYdn9ALY/MRNXV6dn/vw4TSjyZ/2Izj7C0S2wl2hSCvdL6eAYvjD3SCauWlqQQM75b+EZLO6G25KtScmvDjkRlPl6JoT0+DduIHx5N8cSkruhQKiP7mbAliYWC45UTU8Y7pYYvDY1+BHrQQwQ3zcBMVF52ZcTsBt6wYrOaejP0PJSTZy2AIWvEpvHcFy7e27mxlG65vwBK1uO5zdWyMPm+8dtZH0+jWjTzfjQkEnht9VZjASQZRIKxqAy3Uu33dhSvoktHOfazBeLoCAGrc7AqbzoajrYSmkNG5C9fqLbckW/Fb2715jQZQ/qE+V6H/WFMPfEWaTzmzkYqCwO9MhqJNFhPVwAB+oL4YIKK9ok+vEhNmg5h0MvhYaAi7NjdLtassiOcm3aiO5m3joeztDB0wnKu81zR3V/py8JmwdHPIAHXgNF9P8cadySRngbsk2DXAF0i4+nWSbqEbjUfXHaFEM/8mW0bCHspNuM1cdeldQdbadJH8HZ6shLZXvDB6vAv/8AVAt8hHn/EjX3K0/92PSwlaujSTPiMKB55KCyutdkds//uRllD0DK6kD68iZgMo77AOr2WR087aCVTrnToxDEm1oHdJFjCwd0q0dQy6qqCXxvKjzhYc7rM9wxl7sS61IkIPT9vPVMY0LTDHT3+ZKNOua4KiKzvJdTIBWxDHn6f37Ld3yRva7GhNlqAYBq41kXVVmZn3snQZsgmiG7e8nPDtOdWn8bsKlUGygQCjxZMwqjvZ/1SGlNlPHsUIPk8LaPiiKzIlvYoCaYdHBMAImyE1g19/H8pr+l9CisPOGneAnRPrtyXZbu2Qc9SBTQtaoXxGVs3CVzQzEi+Cf0csjLico0e5XFTJRsvmTzV7wBwBctGni9yRA1Y3kciB3FChMPy81pNMWDzYm+lhMfjsMx3d7EGZb/tu4Ys0sEQPty8wmICzYYiXlIzx9aGl5MKFSULere5aF2jS69RUSVJSas2XB7Jxp/hpm2VTGQIaG2AJyfX1Rr5FGTq87dL9oamvApUlx8mK0dd8Mw/CoE2eRU8pp5GAjWOthakWHRapi1u21wJl6b6JEL2mQxGdwvvb2A7WldCaHZ4pcpMTG/OOdWf4lB0COhQd/FNR35/hOYFlUw8QpaCUiY/ZcBbvBodX1kFNHK8MmQvpRuX7LMM8ewr8+pc2OuhIbq95deKb7BWs1S6KiZ8SJSVjyhYCglG6XVOb4pILG9ER/i5yc1QzioUkzSGP02jfdzSXBsckajmGPDW6AO0sa8jWILIBYujIdSNBc0g6b81CrCTXV9swNxVNC8WDDWK91j+BXcM3HTGiqm39krq7nrag3LUBPRwnXhjdJsqO6fU5nxif6GqJ3WhCa7LGpYqalD56jAn8Casbu3EXefyFl/jJBWvR5CSoBufrh5atwzwvRaP5diogIRFDSsSb3i9PpNo37xLhEAPjftWyhBnaRwAUgMKb14ePwbQ1orQBvdHzYbbwuj5ODiavajMlGxMuQ92dIWTsTR5jq9yLNSlHqNWFZzQM7mRfiOmjQ99Z8+axePIxAjVBEOipoQoePvKbV/XerF8TB3D+tFIIFGmKuka0DLHbPs0HSEEKGwUjR/8bStqjPrJ/jfm+ayuJrj6NJbAZARe66e/effs1NtzUZEB0BkA7DTfgCTMNy2Mx8/rlnTD8Wn0beDhujp5brPSdMhr5AgtLAKxBSWYlXvBBCuuoDCIwwsiq6BRLl1PQFettLZYYAOtD0MqiNw0Lb9o/+bI1mwesrGTGl2apCmf9Y8g/M7XmbklPGDj6gV8A3+MA5ndtfiUinJF+6uYrJ/mXyztdLDWnkJdH+x9N/8IRjnQss9vpYDo8vK1R3PgotaVvTgQmLsimYVrVnyLdDjxvd5xiu0J/dFBluwmItpv8hbDgpgEAwmEFNMGTj2xQRxPLGPhS4H8Vi5ViJhoiIWMYV8O6H2rwJyiPhhhbpYImcOjoz5+Jce5CWiw/JKJeCbKHWKX6MoxxJNrs1CMUsyO4qCYPULTtjTG7zc2HCIWhz0GUm/iI57zTPa1EKqWPNjeTR2OELvhuV+0K+nsMb8GxvflRSuJyco5dZjTgV04qHeZvQNQULm7CiMIbghDW8+XLOIeW25vW80ENxhA1tKViKMD6HGLFyXDDtgr9ra14fgRkUzC6WX2VW++pXni/RhPlLNLMixHshSEL8CLXAdvs2kMMRMJmWMMFiBU38MJRmBOwHKJ8eo6okW0MdGeXhAAjAs7VpRle6Vt4cieMOFSiBMFOZYxZLNi8nyM3SuDNl9fWkii0qBRn8N8R+Pd4NHWeeG8nixks/2jM43/A82lTtVO9u7/Y67h0IwiVSON4vwIl0kWKte6FJtlU+r/6u/yfXhEN17nLJOew4dqg/JNSF3M3cYb2EBLKkbGl+N4ZmmkDYZqaA7Eqwp+881qaQspvVWg1pQH3S/qYmUN7FfIri7S9Krmm3Fnznjbf+zphQYkSaYADNI9Muh9N52Gep8MQraaNCpEcgwm/a98bi/ATB2va+qbDZPAD6VBQk1pRxd/Vw64f17uS0HckOuFrEKASIrlmCpW6QSgxnJR+VZGs4JbEHDQRoWXMVBxAgzTNJ9vdA=}"
          scope: GLOBAL
          username: "ubuntu"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "built-in"
  - name: "controller"
  - name: "node1"
  labelString: "controller"
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  nodes:
  - permanent:
      labelString: "node1"
      launcher:
        ssh:
          credentialsId: "ubuntu"
          host: "10.0.1.144"
          port: 22
          sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
      name: "node1"
      numExecutors: 5
      remoteFS: "/home/ubuntu/jenkins_node"
      retentionStrategy: "always"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "artem"
        password: ${JENKINS_ADMIN_PASSWORD}
        name: "Artem Utkin"
        properties:
        - "myView"
        - "timezone"
        - "experimentalFlags"
        - "apiToken"
        - "mailer"
        - preferredProvider:
            providerId: "default"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubPluginConfig:
    hookUrl: "https://ihantala.link/github-webhook/"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "https://ihantala.link/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
jobs:
  - file: /usr/local/seedjob.groovy
